name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.6'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Tests (pytest + coverage)
        run: python -m pytest --cov=app --cov-report=term-missing